CREATE TABLE [dbo].[CallPerformance] (
    [Id]             INT              IDENTITY (1, 1) NOT NULL,
    [TradeType]      VARCHAR (30)     NOT NULL,
    [CallDate]       DATETIME         NOT NULL,
    [CallByKey]      VARCHAR (50)     NULL,
    [StrategyKey]    VARCHAR (50)     NOT NULL,
    [StockKey]       VARCHAR (50)     NOT NULL,
    [SegmentKey]     VARCHAR (50)     NULL,
    [LotSize]        INT              NULL,
    [OptionValue]    VARCHAR (500)    NULL,
    [ExpiryKey]      VARCHAR (50)     NULL,
    [EntryPrice]     DECIMAL (12, 2)  NULL,
    [Target1Price]   DECIMAL (12, 2)  NULL,
    [Target2Price]   DECIMAL (12, 2)  NULL,
    [Target3Price]   DECIMAL (12, 2)  NULL,
    [StopLossPrice]  DECIMAL (12, 2)  NULL,
    [EntryTime]      VARCHAR (20)     NULL,
    [TriggerTime]    VARCHAR (20)     NULL,
    [ExitPrice]      DECIMAL (12, 2)  NULL,
    [ResultHigh]     DECIMAL (12, 2)  NULL,
    [PlottedCapital] DECIMAL (12, 2)  NULL,
    [Pnl]            DECIMAL (12, 2)  NULL,
    [Roi]            DECIMAL (12, 2)  NULL,
    [Remarks]        VARCHAR (500)    NULL,
    [CallStatus]     VARCHAR (50)     NULL,
    [PublicKey]      UNIQUEIDENTIFIER CONSTRAINT [DF_CallPerformance_PublicKey] DEFAULT (newid()) NULL,
    [IsIntraday]     BIT              NULL,
    [ResultTypeKey]  VARCHAR (50)     NULL,
    [IsPublic]       BIT              NULL,
    [IsDisabled]     BIT              NULL,
    [IsDelete]       BIT              NULL,
    [CreatedOn]      DATETIME         NOT NULL,
    [CreatedBy]      VARCHAR (100)    NOT NULL,
    [ModifiedOn]     DATETIME         NULL,
    [ModifiedBy]     VARCHAR (100)    NULL,
    CONSTRAINT [PK__CallPerf__3214EC0768916350] PRIMARY KEY CLUSTERED ([Id] ASC)
);

