CREATE TABLE [dbo].[Leads_shadow] (
    [AuditId]       BIGINT           IDENTITY (1, 1) NOT NULL,
    [Id]            BIGINT           NOT NULL,
    [FullName]      VARCHAR (150)    NULL,
    [MobileNumber]  VARCHAR (100)    NULL,
    [EmailId]       VARCHAR (100)    NULL,
    [ServiceKey]    VARCHAR (100)    NULL,
    [LeadTypeKey]   VARCHAR (100)    NULL,
    [LeadSourceKey] VARCHAR (100)    NULL,
    [Remarks]       VARCHAR (300)    NULL,
    [IsStudent]     TINYINT          NULL,
    [IsCustomer]    TINYINT          NULL,
    [IsSpam]        TINYINT          NULL,
    [IsWon]         TINYINT          NULL,
    [IsDisabled]    TINYINT          NULL,
    [IsDelete]      TINYINT          NULL,
    [PublicKey]     UNIQUEIDENTIFIER NULL,
    [CreatedOn]     DATETIME         NULL,
    [CreatedBy]     VARCHAR (100)    NULL,
    [ModifiedOn]    DATETIME         NULL,
    [ModifiedBy]    VARCHAR (100)    NULL,
    [AssignedTo]    VARCHAR (100)    NULL,
    [AuditAction]   CHAR (1)         NOT NULL,
    [AuditDate]     DATETIME         CONSTRAINT [DF_Leads_shadow_AuditDate] DEFAULT (getdate()) NOT NULL,
    [AuditUser]     VARCHAR (50)     CONSTRAINT [DF_Leads_shadow_AuditUser] DEFAULT (suser_sname()) NOT NULL,
    [AuditApp]      VARCHAR (128)    CONSTRAINT [DF_Leads_shadow_AuditApp] DEFAULT (('App=('+rtrim(isnull(app_name(),'')))+') ') NULL,
    CONSTRAINT [PK_Leads_shadow] PRIMARY KEY CLUSTERED ([AuditId] ASC)
);

