CREATE TABLE [dbo].[Leads] (
    [Id]               BIGINT           IDENTITY (1, 1) NOT NULL,
    [PublicKey]        UNIQUEIDENTIFIER CONSTRAINT [DF__Leads__PublicKey__07C12930] DEFAULT (newsequentialid()) NOT NULL,
    [FullName]         VARCHAR (150)    NULL,
    [Gender]           CHAR (1)         NULL,
    [MobileNumber]     VARCHAR (100)    NOT NULL,
    [EmailId]          VARCHAR (100)    NULL,
    [ProfileImage]     NVARCHAR (MAX)   NULL,
    [PriorityStatus]   VARCHAR (20)     NULL,
    [AssignedTo]       VARCHAR (100)    CONSTRAINT [DF__Leads__AssignedT__0A9D95DB] DEFAULT ('BB74D26F-AA28-EB11-BEE5-00155D53687A') NULL,
    [ServiceKey]       VARCHAR (100)    NULL,
    [LeadTypeKey]      VARCHAR (100)    CONSTRAINT [DF__Leads__LeadTypeK__00200768] DEFAULT ('4C98BD0B-6F08-EB11-BFA7-00155D53687A') NULL,
    [LeadSourceKey]    VARCHAR (100)    CONSTRAINT [DF__Leads__LeadSourc__01142BA1] DEFAULT ('EB82ED26-6708-EB11-BFA7-00155D53687A') NULL,
    [Remarks]          VARCHAR (300)    NULL,
    [IsDisabled]       TINYINT          CONSTRAINT [DF__Leads__IsDisable__05D8E0BE] DEFAULT ((0)) NULL,
    [IsDelete]         TINYINT          CONSTRAINT [DF__Leads__IsDelete__06CD04F7] DEFAULT ((0)) NULL,
    [CreatedOn]        DATETIME         CONSTRAINT [DF__Leads__CreatedOn__08B54D69] DEFAULT (getdate()) NOT NULL,
    [CreatedBy]        VARCHAR (100)    NOT NULL,
    [IsSpam]           TINYINT          CONSTRAINT [DF__Leads__IsSpam__03F0984C] DEFAULT ((0)) NULL,
    [IsWon]            TINYINT          CONSTRAINT [DF__Leads__IsWon__04E4BC85] DEFAULT ((0)) NULL,
    [ModifiedOn]       DATETIME         CONSTRAINT [DF__Leads__ModifiedO__09A971A2] DEFAULT (NULL) NOT NULL,
    [ModifiedBy]       VARCHAR (100)    NOT NULL,
    [City]             VARCHAR (100)    NULL,
    [PinCode]          VARCHAR (15)     NULL,
    [PurchaseOrderKey] UNIQUEIDENTIFIER NULL,
    [StatusId]         INT              NULL,
    CONSTRAINT [PK__Leads__3214EC07DF7B12F4] PRIMARY KEY CLUSTERED ([Id] ASC)
);

