CREATE TABLE [dbo].[PartnerAccounts] (
    [Id]               BIGINT           IDENTITY (1, 1) NOT NULL,
    [FullName]         VARCHAR (150)    NULL,
    [MobileNumber]     VARCHAR (100)    NULL,
    [EmailId]          VARCHAR (100)    NULL,
    [City]             VARCHAR (100)    NULL,
    [Source]           VARCHAR (50)     NULL,
    [AssignedTo]       INT              NULL,
    [TelegramId]       VARCHAR (500)    NULL,
    [ZerodhaCId]       VARCHAR (100)    NULL,
    [AngelCId]         VARCHAR (100)    NULL,
    [AliceBlueCId]     VARCHAR (100)    NULL,
    [EdelweissCId]     VARCHAR (100)    NULL,
    [FyersCId]         VARCHAR (100)    NULL,
    [MotilalCId]       VARCHAR (100)    NULL,
    [Brokerage]        FLOAT (53)       NULL,
    [LeadKey]          VARCHAR (100)    NULL,
    [CustomerKey]      VARCHAR (100)    NULL,
    [Remarks]          VARCHAR (300)    NULL,
    [IsDisabled]       TINYINT          CONSTRAINT [DF__PartnerAc__IsDis__1CBC4616] DEFAULT ((0)) NULL,
    [IsDelete]         TINYINT          CONSTRAINT [DF__PartnerAc__IsDel__1DB06A4F] DEFAULT ((0)) NULL,
    [PublicKey]        UNIQUEIDENTIFIER CONSTRAINT [DF__PartnerAc__Publi__1EA48E88] DEFAULT (newsequentialid()) NULL,
    [CreatedIpAddress] VARCHAR (100)    NULL,
    [CreatedOn]        DATETIME         CONSTRAINT [DF__PartnerAc__Creat__1F98B2C1] DEFAULT (getdate()) NULL,
    [CreatedBy]        VARCHAR (100)    NULL,
    [ModifiedOn]       DATETIME         CONSTRAINT [DF__PartnerAc__Modif__208CD6FA] DEFAULT (NULL) NULL,
    [ModifiedBy]       VARCHAR (100)    NULL,
    [Status]           INT              NULL,
    CONSTRAINT [PK__PartnerA__3214EC0705BC839F] PRIMARY KEY CLUSTERED ([Id] ASC)
);

