CREATE TABLE [dbo].[PurchaseOrders] (
    [Id]                    INT              IDENTITY (1, 1) NOT NULL,
    [PublicKey]             UNIQUEIDENTIFIER CONSTRAINT [DF_PurchaseOrders_PublicKey] DEFAULT (newsequentialid()) NULL,
    [LeadId]                BIGINT           NULL,
    [ClientName]            VARCHAR (50)     NULL,
    [Mobile]                VARCHAR (50)     NULL,
    [Email]                 VARCHAR (50)     NULL,
    [DOB]                   VARCHAR (50)     NULL,
    [Remark]                VARCHAR (200)    NULL,
    [PaymentDate]           DATETIME         NULL,
    [ModeOfPayment]         INT              NULL,
    [BankName]              VARCHAR (100)    NULL,
    [Pan]                   VARCHAR (20)     NULL,
    [State]                 VARCHAR (20)     NULL,
    [City]                  VARCHAR (50)     NULL,
    [TransactionRecipt]     VARCHAR (500)    NULL,
    [TransasctionReference] VARCHAR (100)    NULL,
    [ServiceId]             INT              NULL,
    [Service]               VARCHAR (50)     NULL,
    [NetAmount]             DECIMAL (10, 2)  NULL,
    [PaidAmount]            DECIMAL (10, 2)  NULL,
    [PaymentStatusId]       INT              NULL,
    [PaymentActionDate]     DATETIME         NULL,
    [StartDate]             DATETIME         NULL,
    [EndDate]               DATETIME         NULL,
    [LTCDate]               DATETIME         NULL,
    [IsExpired]             BIT              NULL,
    [Status]                INT              NULL,
    [ActionBy]              UNIQUEIDENTIFIER NULL,
    [CreatedOn]             DATETIME         NULL,
    [CreatedBy]             UNIQUEIDENTIFIER NULL,
    [ModifiedOn]            DATETIME         NULL,
    [ModifiedBy]            UNIQUEIDENTIFIER NULL,
    [IsActive]              BIT              NULL,
    CONSTRAINT [PK__Purchase__3214EC0739F97C3D] PRIMARY KEY CLUSTERED ([Id] ASC)
);

